name: car_rental_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  flutter_svg: ^2.0.17
  flutter_gen: ^5.9.0
  animate_do: ^4.1.1
  app_bar_with_search_switch: ^1.8.6
  pinput: ^5.0.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  flutter_3d_controller: ^2.2.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.1.5
  cloud_firestore: ^6.1.0
  intl: ^0.18.0
  url_launcher: ^6.3.2
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:

  flutter_lints: ^4.0.0

flutter_gen:
  output: lib/core/gen
  line_length: 80

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/onboarding/
    - assets/images/flags/
    - assets/images/
    - assets/icons/
    - assets/3d-models/

  fonts:
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf